export const data = [
    {
        titleHeaderLeft: "Sốt",
        index: 1,
        keyDefine: "sot",
        value: 0,
    },
    {
        titleHeaderLeft: "Nhiệt độ",
        index: 2,
        keyDefine: "nhietDo",
        value: 1,
    },
    //
    {
        titleHeaderLeft: "Ho",
        state_name: "Không ho",
        index: 3,
        keyDefine: "ho",
        value: 0,
    },
    {
        titleHeaderLeft: "Ho",
        state_name: "Ít",
        index: 4,
        keyDefine: "ho",
        value: 1,
    },
    {
        titleHeaderLeft: "Ho",
        state_name: "Vừa",
        index: 5,
        keyDefine: "ho",
        value: 2,
    },
    {
        titleHeaderLeft: "Ho",
        state_name: "Nhiều",
        index: 6,
        keyDefine: "ho",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Đau họng",
        state_name: "Không đau",
        index: 6,
        keyDefine: "dauHong",
        value: 0,
    },
    {
        titleHeaderLeft: "Đau họng",
        state_name: "Nhẹ",
        index: 7,
        keyDefine: "dauHong",
        value: 1,
    },
    {
        titleHeaderLeft: "Đau họng",
        state_name: "Trung bình",
        index: 8,
        keyDefine: "dauHong",
        value: 2,
    },
    {
        titleHeaderLeft: "Đau họng",
        state_name: "Nặng",
        index: 9,
        keyDefine: "dauHong",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Đau người",
        state_name: "Không đau",
        index: 10,
        keyDefine: "dauNguoi",
        value: 0,
    },
    {
        titleHeaderLeft: "Đau người",
        state_name: "Nhẹ",
        index: 11,
        keyDefine: "dauNguoi",
        value: 1,
    },
    {
        titleHeaderLeft: "Đau người",
        state_name: "Trung bình",
        index: 12,
        keyDefine: "dauNguoi",
        value: 2,
    },
    {
        titleHeaderLeft: "Đau người",
        state_name: "Nặng",
        index: 13,
        keyDefine: "dauNguoi",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Đau đầu",
        state_name: "Không đau",
        index: 14,
        keyDefine: "dauDau",
        value: 0,
    },
    {
        titleHeaderLeft: "Đau đầu",
        state_name: "Nhẹ",
        index: 15,
        keyDefine: "dauDau",
        value: 1,
    },
    {
        titleHeaderLeft: "Đau đầu",
        state_name: "Trung bình",
        index: 16,
        keyDefine: "dauDau",
        value: 2,
    },
    {
        titleHeaderLeft: "Đau đầu",
        state_name: "Nặng",
        index: 17,
        keyDefine: "dauDau",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Mệt mỏi",
        state_name: "Không mệt",
        index: 18,
        keyDefine: "metMoi",
        value: 0,
    },
    {
        titleHeaderLeft: "Mệt mỏi",
        state_name: "Mệt nhẹ",
        index: 19,
        keyDefine: "metMoi",
        value: 1,
    },
    {
        titleHeaderLeft: "Mệt mỏi",
        state_name: "Mệt vừa",
        index: 20,
        keyDefine: "metMoi",
        value: 2,
    },
    {
        titleHeaderLeft: "Mệt mỏi",
        state_name: "Rất mệt",
        index: 21,
        keyDefine: "metMoi",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Ớn lạnh",
        state_name: "Không",
        index: 22,
        keyDefine: "onLanh",
        value: 0,
    },
    {
        titleHeaderLeft: "Ớn lạnh",
        state_name: "1-2 lần/ngày",
        index: 23,
        keyDefine: "onLanh",
        value: 1,
    },
    {
        titleHeaderLeft: "Ớn lạnh",
        state_name: "3 - 5 lần",
        index: 24,
        keyDefine: "onLanh",
        value: 2,
    },
    {
        titleHeaderLeft: "Ớn lạnh",
        state_name: "> 5 lần",
        index: 25,
        keyDefine: "onLanh",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Giảm/mất vị giác",
        state_name: "Không",
        index: 26,
        keyDefine: "matViGiac",
        value: 0,
    },
    {
        titleHeaderLeft: "Giảm/mất vị giác",
        state_name: "Ít",
        index: 27,
        keyDefine: "matViGiac",
        value: 1,
    },
    {
        titleHeaderLeft: "Giảm/mất vị giác",
        state_name: "Nhiều",
        index: 28,
        keyDefine: "matViGiac",
        value: 2,
    },
    {
        titleHeaderLeft: "Giảm/mất vị giác",
        state_name: "Không còn",
        index: 29,
        keyDefine: "matViGiac",
        value: 3,
    },
    //
    //
    {
        titleHeaderLeft: "Giảm/mất khứu giác",
        state_name: "Không",
        index: 26,
        keyDefine: "matKhuuGiac",
        value: 0,
    },
    {
        titleHeaderLeft: "Giảm/mất khứu giác",
        state_name: "Ít",
        index: 27,
        keyDefine: "matKhuuGiac",
        value: 1,
    },
    {
        titleHeaderLeft: "Giảm/mất khứu giác",
        state_name: "Nhiều",
        index: 28,
        keyDefine: "matKhuuGiac",
        value: 2,
    },
    {
        titleHeaderLeft: "Giảm/mất khứu giác",
        state_name: "Không còn",
        index: 29,
        keyDefine: "matKhuuGiac",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Khó thở",
        state_name: "Không",
        index: 30,
        keyDefine: "khoTho",
        value: 0,
    },
    {
        titleHeaderLeft: "Khó thở",
        state_name: "Nhẹ",
        index: 31,
        keyDefine: "khoTho",
        value: 1,
    },
    {
        titleHeaderLeft: "Khó thở",
        state_name: "Vừa",
        index: 32,
        keyDefine: "khoTho",
        value: 2,
    },
    {
        titleHeaderLeft: "Khó thở",
        state_name: "Nặng",
        index: 33,
        keyDefine: "khoTho",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Buồn nôn, nôn",
        state_name: "Không",
        index: 34,
        keyDefine: "buonNon",
        value: 0,
    },
    {
        titleHeaderLeft: "Buồn nôn, nôn",
        state_name: "Ít",
        index: 35,
        keyDefine: "buonNon",
        value: 1,
    },
    {
        titleHeaderLeft: "Buồn nôn, nôn",
        state_name: "Vừa",
        index: 36,
        keyDefine: "buonNon",
        value: 2,
    },
    {
        titleHeaderLeft: "Buồn nôn, nôn",
        state_name: "Liên tục",
        index: 37,
        keyDefine: "buonNon",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Tiêu chảy",
        state_name: "Không",
        index: 38,
        keyDefine: "tieuChay",
        value: 0,
    },
    {
        titleHeaderLeft: "Tiêu chảy",
        state_name: "1-2 lần/ngày",
        index: 39,
        keyDefine: "tieuChay",
        value: 1,
    },
    {
        titleHeaderLeft: "Tiêu chảy",
        state_name: "3-5 lần",
        index: 40,
        keyDefine: "tieuChay",
        value: 2,
    },
    {
        titleHeaderLeft: "Tiêu chảy",
        state_name: "> 5 lần",
        index: 41,
        keyDefine: "tieuChay",
        value: 3,
    },
    //
    {
        titleHeaderLeft: "Covid nhanh",
        state_name: "Âm tính",
        index: 42,
        keyDefine: "testNhanh",
        value: -1,
    },
    {
        titleHeaderLeft: "Covid nhanh",
        state_name: "Dương tính",
        index: 43,
        keyDefine: "testNhanh",
        value: 1,
    },
    {
        titleHeaderLeft: "Covid PCR",
        state_name: "Âm tính",
        index: 44,
        keyDefine: "pcr",
        value: -1,
    },
    {
        titleHeaderLeft: "Covid PCR",
        state_name: "Dương tính",
        index: 45,
        keyDefine: "pcr",
        value: 1,
    },
]