export const MA_GIAM_GIA = {
  HINH_THUC_GIAM_GIA: {
    THEO_PHIEU_THU: 10,
    THEO_DICH_VU: 20
  },
  CACH_THUC_GIAM_GIA: {
    GIAM_PHAN_TRAM: 10,
    GIAM_TIEN: 20
  },
  LOAI_AP_DUNG_GIAM_GIA: {
    THEO_NHOM_DICH_VU: 10,
    THEO_DICH_VU: 20
  }
};
